live_config_reload = true

[window]
title = "Alacritty"
startup_mode="Fullscreen"

[font]
size = 6.8
normal = {family = "mononoki"}

[colors]
primary.background = "#000000"

[mouse]
hide_when_typing = true

