alias svi="sudo nvim -u $HOME/.config/nvim/init.lua"
alias vmod="nvim $HOME/.config/nvim/init.lua"
alias cat="$(get_bin_path bat)"
alias ocat="$(get_bin_path cat)"
alias ls="$(get_bin_path eza)"
alias hq="$(get_bin_path htmlq)"
alias ..="cd .."
alias ...="cd ../.."
alias flog="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) -%G?- %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)' --all"
alias sqli="sqlite3 --header --nullvalue '<{nil}>' --column"

