eval "$(direnv hook bash)"

if [ -f ~/.shenv.sh ] ; then
	. ~/.shenv.sh
fi

if [ -z "$COMPUTER_NAME" ] ; then
	if [ -f /etc/hostname ] ; then
		COMPUTER_NAME=$(cat /etc/hostname)
	else
		COMPUTER_NAME="unnamed computer"
	fi
fi

get_bin_path() {
	paths=${2:-$PATH}
	for dr in $(echo $paths | tr ':' '\n') ; do
		if [ -f "$dr/$1" ] ; then
			echo "$dr/$1"
			return 0
		fi
	done
	return 1
}

if [ -d "$DEVAPS" ] ; then
	export PATH="$DEVAPS/bin:$PATH"
fi

export GPG_TTY=$(tty)
export PSQL_EDITOR="$(get_bin_path nvim) -n -u $HOME/.vimrc"
export ZEN="true"
export BAT_THEME="zenburn"
export GOPATH=$HOME/.go
export TERM=xterm-256color
export VISUAL="nvim"
export PAGER="less"
# EDITOR defined in nvim.bash

for module in $HOME/dots/bash/*.bash; do
	source $module
done
