if ! [[ $- = *i* ]] ; then
	source "$HOME"/.shenv.bash
fi

if [ -z "$COMPUTER_NAME" ] ; then
	if [ -f /etc/hostname ] ; then
		COMPUTER_NAME=$(cat /etc/hostname)
	else
		COMPUTER_NAME="unnamed computer"
	fi
fi

source $DOTS/bash/path.sh
get_bin_path() {
	paths=${2:-$PATH}
	for dr in $(echo $paths | tr ':' '\n') ; do
		if [ -f "$dr/$1" ] ; then
			echo "$dr/$1"
			return 0
		fi
	done
	return 1
}

tmod() {
	if [ "$1" = "rc" ] ; then
		$EDITOR $DOTS/bash/bashrc
	elif [ "$1" = "path" ] ; then
		$EDITOR $DOTS/bash/path.sh
	elif [ -n "$1" ] ; then
		$EDITOR $DOTS/bash/$1.bash
	else
		$EDITOR $DOTS/bash/
	fi
	source $DOTS/bash/bashrc
}

__compl_tmod() {
	COMPREPLY=(
		$(compl $DOTS/completions/tmod.compl ${COMP_WORDS[@]:1})
	)
}
complete -F __compl_tmod "tmod"

export GPG_TTY=$(tty)
export PSQL_EDITOR="$(get_bin_path nvim) -n -u $HOME/.vimrc"
export ZEN="true"
export BAT_THEME="zenburn"
export TERM=xterm-256color
export PAGER="less"

for module in $DOTS/bash/*.bash; do
	source $module
done
